export const ADD_ANSWER = "ADD_ANSWER";
export const ADD_ANSWER_SUCCESS = "ADD_ANSWER_SUCCESS";
export const ADD_ANSWER_FAILURE = "ADD_ANSWER_FAILURE";

export const EDIT_ANSWER = "EDIT_ANSWER";
export const EDIT_ANSWER_SUCCESS = "EDIT_ANSWER_SUCCESS";
export const EDIT_ANSWER_FAILURE = "EDIT_ANSWER_FAILURE";

export const DELETE_ANSWER = "DELETE_ANSWER";
export const DELETE_ANSWER_SUCCESS = "DELETE_ANSWER_SUCCESS";
export const DELETE_ANSWER_FAILURE = "DELETE_ANSWER_FAILURE";
