const REGISTER = "REGISTER";
const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const REGISTER_FAILURE = "REGISTER_FAILURE";

const LOGIN = "LOGIN";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAILURE = "LOGIN_FAILURE";

const GET_USER = "GET_USER";
const GET_USER_SUCCESS = "GET_USER_SUCCESS";
const GET_USER_FAILURE = "GET_USER_FAILURE";

const SEND_RESET_LINK = "SEND_RESET_LINK";
const SEND_RESET_LINK_SUCCESS = "SEND_RESET_LINK_SUCCESS";
const SEND_RESET_LINK_FAILURE = "SEND_RESET_LINK_FAILURE";

const RESET_PASSWORD = "RESET_PASSWORD";
const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";

const EDIT_USER = "EDIT_USER";
const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
const EDIT_USER_FAILURE = "EDIT_USER_FAILURE";

const VERIFY_EMAIL = "VERIFY_EMAIL";
const VERIFY_EMAIL_SUCCESS = "VERIFY_EMAIL_SUCCESS";
const VERIFY_EMAIL_FAILURE = "VERIFY_EMAIL_FAILURE";

const VERIFY_EMAIL_CHANGE = "VERIFY_EMAIL_CHANGE";
const VERIFY_EMAIL_CHANGE_SUCCESS = "VERIFY_EMAIL_CHANGE_SUCCESS";
const VERIFY_EMAIL_CHANGE_FAILURE = "VERIFY_EMAIL_CHANGE_FAILURE";

const CHANGE_EMAIL = "CHANGE_EMAIL";
const CHANGE_EMAIL_SUCCESS = "CHANGE_EMAIL_SUCCESS";
const CHANGE_EMAIL_FAILURE = "CHANGE_EMAIL_FAILURE";


const DELETE_USER = "DELETE_USER";
const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";

const LOGOUT = "LOGOUT";

const CLEAR_ERROR = "CLEAR_ERROR";

const SET_STATUS = "SET_STATUS";

const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export {
  REGISTER_FAILURE,
  REGISTER,
  REGISTER_SUCCESS,
  LOGIN,
  LOGIN_FAILURE,
  LOGIN_SUCCESS,
  LOGOUT,
  CLEAR_ERROR,
  SET_STATUS,
  GET_USER_SUCCESS,
  GET_USER_FAILURE,
  GET_USER,
  SEND_RESET_LINK,
  SEND_RESET_LINK_FAILURE,
  SEND_RESET_LINK_SUCCESS,
  RESET_PASSWORD,
  RESET_PASSWORD_FAILURE,
  RESET_PASSWORD_SUCCESS,
  CLEAR_MESSAGE,
  EDIT_USER,
  EDIT_USER_FAILURE,
  EDIT_USER_SUCCESS,
  VERIFY_EMAIL,
  VERIFY_EMAIL_FAILURE,
  VERIFY_EMAIL_SUCCESS,
  VERIFY_EMAIL_CHANGE,
  VERIFY_EMAIL_CHANGE_FAILURE,
  VERIFY_EMAIL_CHANGE_SUCCESS,
  CHANGE_EMAIL,
  CHANGE_EMAIL_FAILURE,
  CHANGE_EMAIL_SUCCESS,
  DELETE_USER,
  DELETE_USER_SUCCESS,
  DELETE_USER_FAILURE,
};
