const ADD_COMMENT = "ADD_COMMENT";
const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
const ADD_COMMENT_FAILURE = "ADD_COMMENT_FAILURE";

export { ADD_COMMENT, ADD_COMMENT_FAILURE, ADD_COMMENT_SUCCESS };
