const LIKE = "LIKE";
const LIKE_SUCCESS = "LIKE_SUCCESS";
const LIKE_FAILURE = "LIKE_FAILURE";

const DISLIKE = "DISLIKE";
const DISLIKE_SUCCESS = "DISLIKE_SUCCESS";
const DISLIKE_FAILURE = "DISLIKE_FAILURE";

export {
  LIKE,
  LIKE_SUCCESS,
  LIKE_FAILURE,
  DISLIKE,
  DISLIKE_SUCCESS,
  DISLIKE_FAILURE
};
